# Generated by Django 5.1.3 on 2024-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('grandfather_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('dob_gregorian', models.DateField(max_length=20, verbose_name='Date of Birth (Gregorian)')),
                ('dob_ethiopian', models.DateField(max_length=20, verbose_name='Date of Birth (Ethiopian)')),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
            ],
        ),
    ]
