# Generated by Django 5.1.3 on 2024-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dob_ethiopian_user_dob_gregorian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob_ethiopian',
            field=models.DateField(max_length=20, verbose_name='Date of Birth (Ethiopian)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob_gregorian',
            field=models.DateField(max_length=20, verbose_name='Date of Birth (Gregorian)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_expiry_date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_issue_date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(max_length=20),
        ),
    ]
